### ISSUE TITLE
libfst.lib is not a valid Win32 application

### ISSUE THREAD

**Issue by cjjjy** [kkm000/openfst#15]
HI ,I RUN YOUR OPENFSTCODE ON VISUAL STDUDIO 2017 ,there is no error ,but when i want to debug the fstcompose.cc which the code in this program ,it occurs the error that 'libfst.lib is not a valid Win32 application...,"
what should i do?????

**Comment by kkm000** [comment]
Set the correct start project in VS. It's name should be highlighted bold.
