### ISSUE TITLE
Error reading SymbolTable

### ISSUE THREAD

**Issue by SamLam0206** [kkm000/openfst#17]
During reading words.txt for decoding on Windows, I met the following error:

ERROR: SymbolTable::ReadText: Bad number of columns (1), file = words.txt, line = 1:<eps 0>

After a quick fix of line 99 of symbol-table.cc from `SplitString(line, separator.c_str(), &col, true);` to 
`SplitString(line, " ", &col, true);`,
the symbol table could be read.

I wonder if I've set something wrong during the compilation which led to the failure of use of fst_field_separator. Thanks for your assistance.

**Comment by kkm000** [comment]
[SplitString uses strpbrk](https://github.com/kkm000/openfst/blob/b441d84/src/lib/util.cc#L22-L32), which treats the string as a set of separator characters, such that any of them is treated as a separator. Given it worked with your change (which is to treat spaces only are separators), then `separator` is set to a string not containing the space among accepted separators. Check what you pass in `SymbolTableTextOptions` to `SplitString` (or, if the error is from an fst* binary, what is passed with the `--fst_field_separator` switch). By default, [both space and tab characters are accepted](https://github.com/kkm000/openfst/blob/b441d84/src/lib/symbol-table.cc#L16); this switch is rarely used. I'd hazard a guess the string was somehow set to empty, or maybe to a tab only, but your file has spaces between words and labels.

If this is from command line and you do use the switch, keep in mind that quoting might be tricky in Windows batch files.

FWIW, I do not think Kaldi scripts ever use this switch to fstcompile.

**Comment by SamLam0206** [comment]
Thanks for the hint. I found that I've committed a careless mistake. Sorry to bother you!

**Comment by kkm000** [comment]
No biggie, you are welcome!
