### ISSUE TITLE
Feature request: Publish package on chocolatey

### ISSUE THREAD

**Issue by msvaillant** [kkm000/openfst#19]
That would be nice for package to be distributed by CLI interface.
Nevertheless, thank you for port OpenFST!

**Comment by kkm000** [comment]
Honestly, I have no idea what that would involve. I have no experience with chocolatey, except I heard the name... What it this about? Are you thinking about sources, or compiled binaries only?

**Comment by msvaillant** [comment]
> Honestly, I have no idea what that would involve. I have no experience with chocolatey, except I heard the name... What it this about? Are you thinking about sources, or compiled binaries only?

It is just package manager for windows (aka apt on ubuntu) so it takes care of packages being up to day, their installation, uninstallation, etc. You don't need to publish sources, just binaries

**Comment by kkm000** [comment]
Given that the binaries are used only in research, and hardly need to be up to date (rather the opposite; you do not want to bring unknowns into your pipeline), I do not really see a point in doing that.

It's possible I'm missing something important. I am wondering, what is your own rationale for this request?

**Comment by kkm000** [comment]
I'm going to close this due to inactivity. Feel free to ping me here if I do not understand why this could be important.
