### ISSUE TITLE
About the license of this repo

### ISSUE THREAD

**Issue by i-lovelife** [kkm000/openfst#21]
Hi, I notice the copyright is added in this repo but no additional license information is added. Is the license of this repo the same as openfst?

**Comment by kkm000** [comment]
Sure, the original license applies, although I've never thought about this much.  Do you think I should make it more prominent?

**Comment by kkm000** [comment]
I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
