### ISSUE TITLE
Cannot find source file when building from source with Cmake

### ISSUE THREAD

**Issue by jurijsk** [kkm000/openfst#26]
Hi, I'm trying to build OpenFst using cmake:

```
~/openfst/build64 cmake -G "Visual Studio 15 2017 Win64" ../
````

and the output is:
```
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- The following ICU libraries were not found:
--   data (required)
--   i18n (required)
--   io (required)
--   test (required)
--   tu (required)
--   uc (required)
-- Failed to find all ICU components 
(missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND)

-- [tones of paths to header files]

-- Configuring done
CMake Error at src/test/CMakeLists.txt:1 (add_executable):
  Cannot find source file:
    fst_test.h
  Tried extensions ...

CMake Error at src/test/CMakeLists.txt:33 (add_executable):
  Cannot find source file:

    algo_test.h
  Tried extensions ...

CMake Error at src/test/CMakeLists.txt:9 (add_executable):
  Cannot find source file:

    weight-tester.h
	Tried extensions ...

CMake Error at src/test/CMakeLists.txt:1 (add_executable):
  No SOURCES given to target: fst_test

CMake Error at src/test/CMakeLists.txt:33 (add_executable):
  No SOURCES given to target: algo_test_minmax

CMake Error at src/test/CMakeLists.txt:17 (add_executable):
  No SOURCES given to target: algo_test_log

CMake Error at src/test/CMakeLists.txt:9 (add_executable):
  No SOURCES given to target: weight_test

CMake Error at src/test/CMakeLists.txt:25 (add_executable):
  No SOURCES given to target: algo_test_tropical

CMake Error at src/test/CMakeLists.txt:41 (add_executable):
  No SOURCES given to target: algo_test_lexicographic

CMake Error at src/test/CMakeLists.txt:49 (add_executable):
  No SOURCES given to target: algo_test_power

CMake Generate step failed.  Build files cannot be regenerated correctly.

```
I belive that in previous version of the repo at least some of the *.h missing from `src/test/` were located next to `cc` files in the same directory and now moved to [src/include/fst/test](https://github.com/kkm000/openfst/tree/winport/src/include/fst/test). While other files, the "No SOURCES given to target" I can not locate at all.

Im not sure sure what is the proper way to fix that. Is there a problem with cmake files or it is because of my environment.

**Environment:**

- windows 10
- cmake: 3.17.0-rc2-win64-x64
- i do have `vcpkg` build and ran [vcpkg integrate install](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#integrate-command)

**Comment by kkm000** [comment]
> other files, the "No SOURCES given to target" I can not locate at all.

If you are talking about these "algo_test_*" messages, it does not look familiar at all. Probably the moved files left targets without any sources at all? 

@jtrmal, do you have time to look at this?

**Comment by jurijsk** [comment]
> If you are talking about these "algo_test_*" messages, it does not look familiar at all. Probably the moved files left targets without any sources at all?

yes, the `algo_test_*` and `weight_test`; those files are not in the repo but mentioned in couple of MakeList.txt and makefiles.

**Comment by jtrmal** [comment]
I'll try over the weekend. Is it some new OpenFST or the original version
(whatever it is). Looks like the structure of the archive has either been
changed or the OP might have moved something?
y.

**Comment by nalbion** [comment]
I'm having the same issue here:
https://github.com/nalbion/vosk-api/runs/672668745?check_suite_focus=true

**Comment by jtrmal** [comment]
guys, sorry I dropped the ball on this -- what version of the openfst are
you using?
y.

**Comment by nalbion** [comment]
https://github.com/kkm000/openfst/pull/22 fixes this

**Comment by jtrmal** [comment]
I merged the fix -- please fetch...

**Comment by jtrmal** [comment]
I will close this, then, I guess....

**Comment by nalbion** [comment]
thanks
