### ISSUE TITLE
Error reading Kaldi's GrammarFst

### ISSUE THREAD

**Issue by SamLam0206** [kkm000/openfst#28]
I tried to construct GrammarFst on Windows but caught this exception:

> Exception thrown: read access violation.
**_Myend** was nullptr. occurred

I used the default GrammarFst constructor:
`GrammarFst *grammar_fst = new GrammarFst(nonterm_phones_offset,
                                             top_fst,
                                             pairs);`

from [https://github.com/kaldi-asr/kaldi/blob/9e0176972ae157a6d2dffe09bcdfe93dac8a921f/src/fstbin/make-grammar-fst.cc#L135-L137](url)

My code works on Linux so I think it's due to the memory mapping of Fst on Windows. I could load individual ConstFst on windows but not the whole GrammarFst. I need to use Kaldi's GrammarFst on Windows. Can you give me some suggestions? Thanks!

**Comment by daanzu** [comment]
I haven't tested this, but may be related to #20.

**Comment by SamLam0206** [comment]
> I haven't tested this, but may be related to #20.

@daanzu Thanks. I fetched your #23 and tested but got no success. All my Fsts were compiled on Linux server but used on Windows machine locally. For HCLG.fst in ConstFst\<StdArc\> it works perfectly on Windows. But if I wrote the same Fst into GrammarFst object, as in [https://github.com/kaldi-asr/kaldi/blob/797905b0140f7169caf3d97c75a1a56a92f67d38/src/fstbin/make-grammar-fst.cc#L139-L141](url) , it couldn't be loaded on Windows and caught the same read access violation as when the GrammarFst was constructed locally on Windows.

**Comment by daanzu** [comment]
FWIW, I don't use `make-grammar-fst`, but I do use a modified version of `GrammarFst` in my own code, loading them with `dynamic_cast<StdConstFst*>(ReadFstKaldiGeneric(filename))`, on Windows.

**Comment by SamLam0206** [comment]
Sorry I found that there's a bug in my code that caused the problem. No issue here.

**Comment by kkm000** [comment]
Come think of it, I need to port extensions too. A slightly different issue, but makes sense.
