### ISSUE TITLE
OpenFST 1.8.0 port

### ISSUE THREAD

**Issue by Forbinn** [kkm000/openfst#40]
Hello,

I would like to know if the version 1.8.0 of OpenFST will be ported on Windows and when?

Regards,

**Comment by kkm000** [comment]
Yes, it sure will. Unfortunately, both maintainers are very busy at the moment. I cannot give you an ETA, unfortunately, but I hope i can get back to this in 4-6 weeks. Other undone work also accumulates because of the current commitment.

**Comment by Forbinn** [comment]
Ok, I understand and the timing you gave me is more than enough.
Thank you for your work.
