### ISSUE TITLE
["-Wno-sign-compare", Wno-unused-local-typedefs] dont work in visual studio compiler

### ISSUE THREAD

**Issue by kschmid23** [kkm000/openfst#49]
["-Wno-sign-compare", Wno-unused-local-typedefs] falgs dont work in visual studio compiler

**Comment by kkm000** [comment]
Sorry, but we don't support Bazel build, these files are from the original. CMake and VS2019+ are supported.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
