### ISSUE TITLE
MappedFile functionality replaced with NULL

### ISSUE THREAD

**Issue by yonatankahana** [kkm000/openfst#8]
Hi!
I succedded compile Kaldi with your port of OpenFST and I cant load HCLG model because you changed the method to return always null: https://github.com/kkm000/openfst/blob/win/1.6/src/lib/mapped-file.cc
there is a reason for that change? how can I make my Kaldi code work now?

**Comment by jtrmal** [comment]
Can you point us to the Kaldi code that is using MappedFile?
y.

**Comment by yonatankahana** [comment]
```
fst::internal::ConstFstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> >,unsigned int>::Read(std::basic_istream<char,std::char_traits<char> > & strm, const fst::FstReadOptions & opts) Line 213	C++	Symbols loaded.
 	my.dll!fst::ConstFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >,unsigned int>::Read(std::basic_istream<char,std::char_traits<char> > & strm, const fst::FstReadOptions & opts) Line 274	C++	Symbols loaded.
>	my.dll!fst::ReadFstKaldiGeneric(std::basic_string<char,std::char_traits<char>,std::allocator<char> > rxfilename, bool throw_on_err) Line 76	C++	Symbols loaded.
```

basically the entry for this issue in this stacktrace comes from 'ReadFstKaldiGeneric'.

**Comment by jtrmal** [comment]
OK, but IIRC we have decided not to use the mem mapping in kaldi so I'm
asking what kaldi binary source code does this or if it's your own code.
y.

**Comment by jtrmal** [comment]
OK, I'm looking at the OpenFST code of ConstFst and I think I see the issue -- while it does not enforce to use MAP mode, it will always use the MappedFile. 
@yonatankahana You can backport the code from older ports of OpenFST -- at this time I don't really have too much time nor easy access to win machine. Or maybe @kkm000 might have time but he's usually very busy as well.

**Comment by yonatankahana** [comment]
you can see in the file online-nnet2-decoding.h:
there is a class called "SingleUtteranceNnet2Decoder" which its constructor 
```
  SingleUtteranceNnet2Decoder(const OnlineNnet2DecodingConfig &config,
                              const TransitionModel &tmodel,
                              const nnet2::AmNnet &model,
                              const fst::Fst<fst::StdArc> &fst,
                              OnlineFeatureInterface *feature_pipeline);
```
this method wants an fst::Fst<fst::StdArc>
which can be only created with ReadFstKaldiGeneric.

**Comment by kkm000** [comment]
Yeah, it has been my impression that ConstFst had to use mapped memory. It's a very natural candidate for it.

I'll write a (nonmapping) replacement for it today or tomorrow.

Use the vector fst as the workaround meanwhile.

-kkm

On 6 Dec 2017 8:51 a.m., yonatankahana <notifications@github.com> wrote:

you can see in the file online-nnet2-decoding.h:
there is a class called "SingleUtteranceNnet2Decoder" which its constructor

  SingleUtteranceNnet2Decoder(const OnlineNnet2DecodingConfig &config,
                              const TransitionModel &tmodel,
                              const nnet2::AmNnet &model,
                              const fst::Fst<fst::StdArc> &fst,
                              OnlineFeatureInterface *feature_pipeline);


this method wants an fst::Fstfst::StdArc
which can be only created with ReadFstKaldiGeneric.

**Comment by kkm000** [comment]
Please pull latest code from win/1.6. I have restored the original mapped-file.cc, but disabled code paths actually trying to map the file before allocating memory and reading data into it.

If that does not cover it (and it should, generally), I can implement actual mapping with Win32 functions. But MSVC does not have a compatible mmap(), this is a bit more work than I can dedicte myself to at this moment.

/cc @jtrmal. [Change against the original file](https://github.com/kkm000/openfst/compare/orig/1.6...win/1.6#diff-4a064085f70f09f445c96341df324a37)

**Comment by Excalib88** [comment]
I am sorry, but i have problem with openfst. Who can help me please. I cannot load HCLG model on Windows https://pastebin.com/NtaswnAA
